### ISSUE TITLE
Missing short name of behavior

### ISSUE THREAD

**Issue by 1letter** [collective/collective.easyformplugin.registration#2]
The behavior has no shortname. Like in [plone.behavior](https://github.com/plone/plone.behavior#zcml-reference) described:

> Convenience lookup name for this behavior (optional). The behavior will be always registered under the dotted name of provides attribute. This are usally long names. name is a short name for this. If name is given the behavior is registered additional under it. Anyway using short namespaces in name is recommended.

**Comment by cekk** [comment]
@1letter thanks, you're right!

Can you please add it and create a pr?

**Comment by 1letter** [comment]
yes, i can do this sometime in this week.
